from typing import Literal

from yfinance import EquityQuery, FundQuery


MAX_PROFILE_PICTURE_FILE_SIZE_KB = 300

MAX_BANNER_IMAGE_FILE_SIZE_KB = 800

WATCHLIST_GROUP_KEYS = ["created", "forked", "shared", "bookmarked"]

RESERVED = {
    "@",
    "me",
    "profile",
    "settings",
    "account",
    "dashboard",
    "login",
    "logout",
    "signup",
    "register",
    "password",
    "forgot",
    "reset",
    "verify",
    "2fa",
    "mfa",
    "auth",
    "oauth",
    "callback",
    "callbacks",
    "admin",
    "root",
    "sysadmin",
    "staff",
    "support",
    "help",
    "moderator",
    "mod",
    "team",
    "teams",
    "dev",
    "developer",
    "developers",
    "api",
    "v1",
    "v2",
    "graphql",
    "docs",
    "status",
    "health",
    "metrics",
    "ping",
    "webhook",
    "webhooks",
    "static",
    "assets",
    "img",
    "images",
    "css",
    "js",
    "fonts",
    "media",
    "uploads",
    "cdn",
    "robots",
    "sitemap",
    "favicon",
    "well-known",
    "about",
    "privacy",
    "terms",
    "legal",
    "security",
    "policies",
    "pricing",
    "jobs",
    "careers",
    "press",
    "blog",
    "news",
    "contact",
    "new",
    "create",
    "edit",
    "delete",
    "update",
    "report",
    "reports",
    "billing",
    "payments",
    "subscribe",
    "unsubscribe",
    "owner",
    "system",
    "service",
    "bot",
    "null",
    "undefined",
    "none",
    "true",
    "false",
    "con",
    "prn",
    "aux",
    "nul",
    *{f"com{i}" for i in range(1, 10)},
    *{f"lpt{i}" for i in range(1, 10)},
}

WATCHLIST_VISIBILITY = Literal["private", "public", "shared"]

STOCK_INTERVALS = {
    "1m",
    "2m",
    "5m",
    "15m",
    "30m",
    "60m",
    "90m",
    "1h",
    "1d",
    "5d",
    "1wk",
    "1mo",
    "3mo",
}

STOCK_PERIODS = {"1d", "5d", "1mo", "3mo", "6mo", "1y", "2y", "5y", "ytd", "max"}

MARKETS = {
    "US",
    "GB",
    "ASIA",
    "EUROPE",
    "RATES",
    "COMMODITIES",
    "CURRENCIES",
    "CRYPTOCURRENCIES",
}

REGIONS = {
    "ar",
    "at",
    "au",
    "be",
    "br",
    "ca",
    "ch",
    "cl",
    "cn",
    "co",
    "cz",
    "de",
    "dk",
    "ee",
    "eg",
    "es",
    "fi",
    "fr",
    "gb",
    "gr",
    "hk",
    "hu",
    "id",
    "ie",
    "il",
    "in",
    "is",
    "it",
    "jp",
    "kr",
    "kw",
    "lk",
    "lt",
    "lv",
    "mx",
    "my",
    "nl",
    "no",
    "nz",
    "pe",
    "ph",
    "pk",
    "pl",
    "pt",
    "qa",
    "ro",
    "ru",
    "sa",
    "se",
    "sg",
    "sr",
    "sw",
    "th",
    "tr",
    "tw",
    "us",
    "ve",
    "vn",
    "za",
}

EXCHANGES = {
    "ar": ["BUE"],
    "at": ["VIE"],
    "au": ["ASX"],
    "be": ["BRU"],
    "br": ["SAO"],
    "ca": ["CNQ", "NEO", "TOR", "VAN"],
    "ch": ["EBS"],
    "cl": ["SGO"],
    "cn": ["SHH", "SHZ"],
    "co": ["BVC"],
    "cz": ["PRA"],
    "de": ["BER", "DUS", "FRA", "GER", "HAM", "MUN", "STU"],
    "dk": ["CPH"],
    "ee": ["TAL"],
    "eg": ["CAI"],
    "es": ["MCE"],
    "fi": ["HEL"],
    "fr": ["PAR"],
    "gb": ["AQS", "IOB", "LSE"],
    "gr": ["ATH"],
    "hk": ["HKG"],
    "hu": ["BUD"],
    "id": ["JKT"],
    "ie": ["ISE"],
    "il": ["TLV"],
    "in": ["BSE", "NSI"],
    "is": ["ICE"],
    "it": ["MIL"],
    "jp": ["FKA", "JPX", "SAP"],
    "kr": ["KOE", "KSC"],
    "kw": ["KUW"],
    "lk": [],
    "lt": ["LIT"],
    "lv": ["RIS"],
    "mx": ["MEX"],
    "my": ["KLS"],
    "nl": ["AMS"],
    "no": ["OSL"],
    "nz": ["NZE"],
    "pe": [],
    "ph": ["PHP", "PHS"],
    "pk": [],
    "pl": ["WSE"],
    "pt": ["LIS"],
    "qa": ["DOH"],
    "ro": ["BVB"],
    "ru": [],
    "sa": ["SAU"],
    "se": ["STO"],
    "sg": ["SES"],
    "sr": [],
    "sw": ["EBS"],
    "th": ["SET"],
    "tr": ["IST"],
    "tw": ["TAI", "TWO"],
    "us": [
        "ASE",
        "BTS",
        "CXI",
        "NCM",
        "NGM",
        "NMS",
        "NYQ",
        "OEM",
        "OQB",
        "OQX",
        "PCX",
        "PNK",
        "YHD",
    ],
    "ve": ["CCS"],
    "vn": [],
    "za": ["JNB"],
}

SECTORS = {
    "basic-materials",
    "communication-services",
    "consumer-cyclical",
    "consumer-defensive",
    "energy",
    "financial-services",
    "healthcare",
    "industrials",
    "real-estate",
    "technology",
    "utilities",
}

SECTOR_INDUSTRY_MAP = {
    "basic-materials": [
        "agricultural-inputs",
        "aluminum",
        "building-materials",
        "chemicals",
        "coking-coal",
        "copper",
        "gold",
        "lumber-wood-production",
        "other-industrial-metals-mining",
        "other-precious-metals-mining",
        "paper-paper-products",
        "silver",
        "specialty-chemicals",
        "steel",
    ],
    "communication-services": [
        "advertising-agencies",
        "broadcasting",
        "electronic-gaming-multimedia",
        "entertainment",
        "internet-content-information",
        "publishing",
        "telecom-services",
    ],
    "consumer-cyclical": [
        "apparel-manufacturing",
        "apparel-retail",
        "auto-manufacturers",
        "auto-parts",
        "auto-truck-dealerships",
        "department-stores",
        "footwear-accessories",
        "furnishings-fixtures-appliances",
        "gambling",
        "home-improvement-retail",
        "internet-retail",
        "leisure",
        "lodging",
        "luxury-goods",
        "packaging-containers",
        "personal-services",
        "recreational-vehicles",
        "residential-construction",
        "resorts-casinos",
        "restaurants",
        "specialty-retail",
        "textile-manufacturing",
        "travel-services",
    ],
    "consumer-defensive": [
        "beverages-brewers",
        "beverages-non-alcoholic",
        "beverages-wineries-distilleries",
        "confectioners",
        "discount-stores",
        "education-training-services",
        "farm-products",
        "food-distribution",
        "grocery-stores",
        "household-personal-products",
        "packaged-foods",
        "tobacco",
    ],
    "energy": [
        "oil-gas-drilling",
        "oil-gas-e-p",
        "oil-gas-equipment-services",
        "oil-gas-integrated",
        "oil-gas-midstream",
        "oil-gas-refining-marketing",
        "thermal-coal",
        "uranium",
    ],
    "financial-services": [
        "asset-management",
        "banks-diversified",
        "banks-regional",
        "capital-markets",
        "credit-services",
        "financial-conglomerates",
        "financial-data-stock-exchanges",
        "insurance-brokers",
        "insurance-diversified",
        "insurance-life",
        "insurance-property-casualty",
        "insurance-reinsurance",
        "insurance-specialty",
        "mortgage-finance",
        "shell-companies",
    ],
    "healthcare": [
        "biotechnology",
        "diagnostics-research",
        "drug-manufacturers-general",
        "drug-manufacturers-specialty-generic",
        "health-information-services",
        "healthcare-plans",
        "medical-care-facilities",
        "medical-devices",
        "medical-distribution",
        "medical-instruments-supplies",
        "pharmaceutical-retailers",
    ],
    "industrials": [
        "aerospace-defense",
        "airlines",
        "airports-air-services",
        "building-products-equipment",
        "business-equipment-supplies",
        "conglomerates",
        "consulting-services",
        "electrical-equipment-parts",
        "engineering-construction",
        "farm-heavy-construction-machinery",
        "industrial-distribution",
        "infrastructure-operations",
        "integrated-freight-logistics",
        "marine-shipping",
        "metal-fabrication",
        "pollution-treatment-controls",
        "railroads",
        "rental-leasing-services",
        "security-protection-services",
        "specialty-business-services",
        "specialty-industrial-machinery",
        "staffing-employment-services",
        "tools-accessories",
        "trucking",
        "waste-management",
    ],
    "real-estate": [
        "real-estate-development",
        "real-estate-diversified",
        "real-estate-services",
        "reit-diversified",
        "reit-healthcare-facilities",
        "reit-hotel-motel",
        "reit-industrial",
        "reit-mortgage",
        "reit-office",
        "reit-residential",
        "reit-retail",
        "reit-specialty",
    ],
    "technology": [
        "communication-equipment",
        "computer-hardware",
        "consumer-electronics",
        "electronic-components",
        "electronics-computer-distribution",
        "information-technology-services",
        "scientific-technical-instruments",
        "semiconductor-equipment-materials",
        "semiconductors",
        "software-application",
        "software-infrastructure",
        "solar",
    ],
    "utilities": [
        "utilities-diversified",
        "utilities-independent-power-producers",
        "utilities-regulated-electric",
        "utilities-regulated-gas",
        "utilities-regulated-water",
        "utilities-renewable",
    ],
}

SCREENER_LOGICAL_OPERATORS = {
    "Equals": "eq",
    "And": "and",
    "Or": "or",
    "Is in": "is-in",
    "Between": "btwm",
    "Greater than": "gt",
    "Less than": "lt",
    "Greater than or equal to": "gte",
    "Less than or equal to": "lte",
}

CURATED_EQUITY_SCREENERS = {
    "popular": {
        "sort_field": "dayvolume",
        "sort_asc": False,
        "query": EquityQuery(
            "and",
            [
                EquityQuery("gte", ["intradaymarketcap", 2000000000]),
                EquityQuery("gt", ["dayvolume", 5000000]),
                EquityQuery("gte", ["intradayprice", 5]),
                EquityQuery("gte", ["intradaypricechange", 0]),
                EquityQuery("is-in", ["region", "us", "au"]),
            ],
        ),
    },
    "trending": {
        "sort_field": "percentchange",
        "sort_asc": False,
        "query": EquityQuery(
            "and",
            [
                EquityQuery("gte", ["intradaymarketcap", 2000000000]),
                EquityQuery("gt", ["percentchange", 2]),
                EquityQuery("is-in", ["region", "us", "au"]),
            ],
        ),
    },
}

CURATED_FUND_SCREENERS = {
    "popular": {
        "sort_field": "fundnetassets",
        "sort_asc": False,
        "query": FundQuery(
            "and",
            [
                FundQuery("is-in", ["performanceratingoverall", 4, 5]),
                FundQuery("lte", ["initialinvestment", 100000]),
                FundQuery("is-in", ["exchange", "NAS"]),
                FundQuery("eq", ["categoryname", "Large Growth"]),
            ],
        ),
    },
}
